name: "CI"
on:
  push:
    branches: ['**']
  pull_request:
  release:
    types: [published]
  schedule:
  - cron: "19 1 * * 1"

jobs:
  cargo-workflow:
    name: "CI"
    uses: ./.github/workflows/cargo-workflow.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
